server:
  port: 12202
  tomcat:
    uri-encoding: UTF-8
spring:
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181
  application:
    name: serviceclient2


###-----------------------euraka相关配置--------------------------###
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:12120/eureka
    # 表示eureka client间隔多久去拉取服务注册信息，默认为30秒，
    registry-fetch-interval-seconds: 1



